/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/biometric-settings`; params?: Router.UnknownInputParams; } | { pathname: `/livraison-confirmation`; params?: Router.UnknownInputParams; } | { pathname: `/mission-detail`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/theme-settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useBiometrics`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useGpsTracking`; params?: Router.UnknownInputParams; } | { pathname: `/utils/biometricUtils`; params?: Router.UnknownInputParams; } | { pathname: `/utils/secureStoreWeb`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/biometric-settings`; params?: Router.UnknownOutputParams; } | { pathname: `/livraison-confirmation`; params?: Router.UnknownOutputParams; } | { pathname: `/mission-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/theme-settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useBiometrics`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useGpsTracking`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/biometricUtils`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/secureStoreWeb`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/biometric-settings${`?${string}` | `#${string}` | ''}` | `/livraison-confirmation${`?${string}` | `#${string}` | ''}` | `/mission-detail${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/theme-settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/hooks/useBiometrics${`?${string}` | `#${string}` | ''}` | `/hooks/useGpsTracking${`?${string}` | `#${string}` | ''}` | `/utils/biometricUtils${`?${string}` | `#${string}` | ''}` | `/utils/secureStoreWeb${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/biometric-settings`; params?: Router.UnknownInputParams; } | { pathname: `/livraison-confirmation`; params?: Router.UnknownInputParams; } | { pathname: `/mission-detail`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/theme-settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useBiometrics`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useGpsTracking`; params?: Router.UnknownInputParams; } | { pathname: `/utils/biometricUtils`; params?: Router.UnknownInputParams; } | { pathname: `/utils/secureStoreWeb`; params?: Router.UnknownInputParams; };
    }
  }
}
